org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

minecraft_version=1.20.1
minecraft_version_range=[1.20.1,1.21)
forge_version=47.3.0
forge_version_range=[47,)
loader_version_range=[47,)
mapping_channel=official
mapping_version=1.20.1

mod_id=neoprismaticos
mod_name=RPG Classes - Superhero System
mod_license=All Rights Reserved
mod_version=1.0.0
mod_group_id=com.martaviadev.neoprismaticos
mod_authors=mArtav.dev
mod_description=Sistema de clases RPG. Elige tu personaje al entrar al mundo y obtén sus habilidades únicas.